### PR TITLE
Add uniqueness and formatting constraints to x509 for api_subject

### LINKED ISSUE #8: Enforce format of APISubject x509_cn
x509_cn values should look like this:

```ruby
validates :x509_cn, presence: true, format: { with: /\A[\w-]+\z/ }, uniqueness: true
```

The specs which Gumboot shares with client apps should enforce this so that apps don't need to do it themselves i.e ausaccessfed/spin#6

### PR DESCRIPTION
**Pull request by JakeSchoermer**
Added documentation to README conveying new uniqueness requirement and
added new spec to verify that this constraint applies to resolve issue raised in [PR for downstream app](https://github.com/ausaccessfed/validator-service/pull/5).

Closes #8

### CODE REVIEW

**Comment by JakeSchoermer** [comment]
I noticed that [this issue was raised](https://github.com/ausaccessfed/aaf-gumboot/issues/8). Separately from the comment in [my PR for the Validator Service app](https://github.com/ausaccessfed/validator-service/pull/5).

This PR currently addresses the uniqueness issue, but not that format issue. I was not asked to address that format issue in this PR, but think this would be a suitable change to make concurrently.

Do you agree @bradleybeddoes? If so I will do the additional work required here and update my PR.

**Comment by bradleybeddoes** [comment]
Yep, solving #8 whilst you're in this section of code would be a welcome addition @JakeSchoermer

**Comment by JakeSchoermer** [comment]
@bradleybeddoes, this is ready to review whenever you are ready.

**Comment by bradleybeddoes** [comment]
@JakeSchoermer can you please update the commit message body for 8f9fc3a to both link to and close #8 as we've previously discussed using Github Flavoured Markdown.

At the same time tweak the naming of this PR so it represents the full scope of what it does now.

**Comment by JakeSchoermer** [comment]
Ok @bradleybeddoes that's all done now.

**Pull request merged**
